### PR TITLE
Fix Uncached query on every page load

### PR DESCRIPTION
**Pull request by spacedmonkey**
Replace `WP_Query` with `get_page_by_path`. This does two things. 

- `get_page_by_path` it cached by core. The query it does on the database is much simplier and cleaner, making this faster. 
- Makes this function much smaller. 

Fixes: #27

### CODE REVIEW

**Comment by spacedmonkey** [comment]
Thanks for the merge @fklein-lu . Any chance of a tagging a 0.4.1 release, so I can update my composer file and get this live?

**Comment by fklein-lu** [comment]
@spacedmonkey Done.

**Comment by spacedmonkey** [comment]
@fklein-lu I just tired to update my via composer and was unable to download 0.4.1. Seems like packagist was no updated - https://packagist.org/packages/humanmade/hm-redirects .  CC @rmccue as he is wise in all things.

**Comment by rmccue** [comment]
Alas, I don't have admin access to this package (Packagist's permissions are so strange), so can't set up the hooks or anything :(

**Pull request merged**
