### PR TITLE
Add trailing slash to TO filed, fix #74

### LINKED ISSUE #74: trailing-slash for local URL
WP common configuration adds a trailing-slash to URL.
`trailingslashit` is in charge for this.

When redirecting to a local URL, omitting the trailing-slash incur another redirect for the purpose of adding the slash.
The current code always drop that slash implying **two** redirections.

### PR DESCRIPTION
**Pull request by nanastia**
fix #74

### CODE REVIEW

**Review by roborourke — APPROVED** [review]
I think this makes sense to preserve the intended TO value and not assume the URL should work without the slash 👍 

Thanks for fixing!

**Comment by svandragt** [comment]
Looks like the failing docker check is being addressed via https://github.com/humanmade/hm-redirects/pull/83 after that we can retry the check to make sure the tests are passing.

**Comment by nanastia** [comment]
@roborourke @svandragt it's ready to be merged to `master`

**Comment by drzraf** [comment]
What do you think about https://github.com/humanmade/hm-redirects/commit/1ff36b12b7e792392f1c1e57e2b6580561360408 ?

Forcefully appending a trailing `/` (even if there was none), **if** it's a local URL (starting with a `/`)?

**Comment by svandragt** [comment]
@drzraf We responded in https://github.com/humanmade/hm-redirects/issues/74, I think we're going a bit in circles with it. if there is still an issue with the latest release, open a ticket with an example and i'll look into it.

**Comment by drzraf** [comment]
Dears,
I'm sorry but this PR was mostly wrong.

The new block was added to `sanitise_and_normalise_url` which is used to process the `$from` URL inside `get_redirect_uri()`.

But:
1. The `trailingslashit` block was added **before** the query-string is even stripped, as such it misses its point when `$from` contains a query-string
2. It's wrong because `$from` URL are sanitized before being stored into the database (using `normalise_url()` which use `untrailingslashit()`). As a consequence `$from` mechanically can **not** contain a trailing / (nor a query-string)
3. It does **not** fix #74 (but was merged under less than 3 days anyway)

**Comment by drzraf** [comment]
This commit brought a major regression:
```
### /source/
< HTTP/1.1 302 Found
< X-HM-Redirects: true
< Location: https://destination/

### /source
< HTTP/1.1 302 Found
< X-HM-Redirects: true
< Location: https://destination/

### /source/?some_param=foo            <--- trailing-slash + query-string
< HTTP/1.1 404 Not Found                  => HM-redirect misses it

### /source?some_param=foo
< HTTP/1.1 302 Found
< X-HM-Redirects: true
< Location: https://destination/?some_param=foo
```

**Pull request merged**
